<footer class="bg-dark text-light py-4">
    <div class="container text-center">
        <p class="mb-0">&copy; <?= date('Y') ?> Biblioteca Web. Todos los derechos reservados.</p>
        <p class="mb-0">Desarrollado por GIL AGUSTINA</p>
        <p class="mb-0">Desarrollado por LEGUIZA FRANCO</p>
        <div class="mt-2">
            <a href="privacy" class="text-light">Política de Privacidad</a> |
            <a href="terms" class="text-light">Términos de Servicio</a>
        </div>
    </div>
</footer>