<?php
require_once './templates/layouts/header.phtml';
?>
<div class="container mt-4">
    <h1 class="text-center mb-4">Libros del género: <?= htmlspecialchars(ucfirst($result['genero']->genero), ENT_QUOTES, 'UTF-8'); ?></h1>

    <div class="row">
        <?php foreach ($result['libros'] as $book): ?>
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card h-100 shadow-sm">
                    <img src="<?= htmlspecialchars($book->imagen_url, ENT_QUOTES, 'UTF-8'); ?>"
                        class="card-img-top img-fluid mb-3"
                        style="max-width: 80%; height: auto; margin: 0 auto;"
                        alt="Imagen de <?= htmlspecialchars($book->titulo, ENT_QUOTES, 'UTF-8'); ?>">
                    <div class="card-body">
                        <h5 class="card-title"><?= htmlspecialchars($book->titulo, ENT_QUOTES, 'UTF-8'); ?></h5>
                        <a href="bookDetail/<?= htmlspecialchars($book->id, ENT_QUOTES, 'UTF-8'); ?>" class="btn btn-outline-primary mt-3">Ver Detalle</a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<?php

?>