<?php require_once './templates/layouts/header.phtml'; ?>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-lg rounded">
                <img src="<?= htmlspecialchars($book->imagen_url, ENT_QUOTES, 'UTF-8'); ?>"
                    class="card-img-top img-fluid"
                    style="max-width: 60%; height: auto; margin: 0 auto;"
                    alt="Imagen de <?= htmlspecialchars($book->titulo, ENT_QUOTES, 'UTF-8'); ?>">
                <div class="card-body">
                    <div class="card-body">
                        <h3 class="card-title"><?= htmlspecialchars($book->titulo, ENT_QUOTES, 'UTF-8'); ?></h3>
                        <p class="card-text mb-3"><strong>Sinopsis:</strong> <?= htmlspecialchars($book->sinopsis, ENT_QUOTES, 'UTF-8'); ?></p>
                        <p class="card-text mb-3"><strong>Autor:</strong> <?= htmlspecialchars($book->autor, ENT_QUOTES, 'UTF-8'); ?></p>
                        <p class="card-text mb-3"><strong>Año de Publicación:</strong> <?= htmlspecialchars($book->anio_publicacion, ENT_QUOTES, 'UTF-8'); ?></p>
                        <p class="card-text mb-3"><strong>Género:</strong> <?= ucfirst(htmlspecialchars($book->nombre_genero, ENT_QUOTES, 'UTF-8')); ?></p>
                        <a href="home" class="btn btn-outline-primary mt-3">Volver</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php

    ?>