<?php

require_once './templates/header.phtml';
?>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card text-center shadow-sm">
                <div class="card-body">
                    <h1 class="card-title text-danger">¡Error!</h1>
                    <p class="card-text"><?= $message; ?></p>
                    <a href="home" class="btn btn-primary mt-3">Ir a Inicio</a>
                </div>
            </div>
        </div>
    </div>
</div>