<?php require 'templates/layouts/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?>
    </div>
<?php endif; ?>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-sm">
                <div class="card-body">
                    <form method='post' action='login'>
                        <div class='form-group'>
                            <label for='email'>Email</label>
                            <input type='email' class='form-control' id='email' name='email' value="<?php echo isset($_POST['email']) ? htmlspecialchars($_POST['email'], ENT_QUOTES, 'UTF-8') : ''; ?>" required>
                        </div>
                        <div class='form-group'>
                            <label for='password'>Contraseña</label>
                            <input type='password' class='form-control' id='password' name='password' required>
                        </div>
                        <div class="d-flex justify-content-between mt-4 mb-4">
                            <button type='submit' class='btn btn-primary btn-block'>Login</button>
                            <div class="form-check mt-3">
                                <input type="checkbox" class="form-check-input" id="showPassword">
                                <label class="form-check-label" for="showPassword">Mostrar contraseña</label>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // Script para mostrar/ocultar la contraseña
    document.getElementById('showPassword').addEventListener('change', function() {
        const passwordInput = document.getElementById('password');
        passwordInput.type = this.checked ? 'text' : 'password';
    });
</script>