<?php require 'templates/layouts/header.phtml' ?>

<div class="container mt-4">
    <h1 class="text-center mb-4">Agregar Género</h1>
    <?php if (!empty($errors)): ?>
        <div class="alert alert-danger">
            <ul>
                <?php foreach ($errors as $error): ?>
                    <li><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <form action="addGenre" method="POST">

        <div class="mb-3">
            <label for="genero" class="form-label">Género</label>
            <input type="text" class="form-control" id="genero" name="genero" required>
        </div>
        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripción</label>
            <textarea class="form-control" id="descripcion" name="descripcion" required></textarea>
        </div>
        <div class="mb-3">
            <label for="generos_relacionados" class="form-label">Generos Relacionados</label>
            <input type="text" class="form-control" id="generos_relacionados" name="generos_relacionados" required>
        </div>
        <div class="mb-3">
            <label for="nivel_popularidad" class="form-label">Nivel de Popularidad</label>
            <input type="number" class="form-control" id="nivel_popularidad" name="nivel_popularidad" required>
        </div>
        <button type="submit" class="btn btn-primary">Agregar Género</button>
    </form>

</div>