<?php
require_once './templates/layouts/header.phtml';
?>

<div class="container mt-4">
    <h1 class="text-center mb-4">Editar Libro</h1>
    <?php if (!empty($errors)): ?>
        <div class="alert alert-danger">
            <ul>
                <?php foreach ($errors as $error): ?>
                    <li><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <!-- Formulario de edición de libro -->
    <form action="updateBook/<?= $book->id ?>" method="POST">
        <div class="mb-3">
            <label for="titulo" class="form-label">Título</label>
            <input type="text" name="titulo" id="titulo" class="form-control" value="<?= htmlspecialchars($book->titulo, ENT_QUOTES, 'UTF-8'); ?>" required>
        </div>

        <div class="mb-3">
            <label for="sinopsis" class="form-label">Sinopsis</label>
            <textarea name="sinopsis" id="sinopsis" class="form-control" rows="4" required><?= htmlspecialchars($book->sinopsis, ENT_QUOTES, 'UTF-8'); ?></textarea>
        </div>

        <div class="mb-3">
            <label for="autor" class="form-label">Autor</label>
            <input type="text" name="autor" id="autor" class="form-control" value="<?= htmlspecialchars($book->autor, ENT_QUOTES, 'UTF-8'); ?>" required>
        </div>

        <div class="mb-3">
            <label for="anio" class="form-label">Año de Publicación</label>
            <input type="number" name="anio" id="anio" class="form-control" value="<?= $book->anio_publicacion ?>" required>
        </div>

        <div class="mb-3">
            <label for="id_genero" class="form-label">Género</label>
            <select name="id_genero" id="id_genero" class="form-select" required>
                <?php foreach ($genres as $genre): ?>
                    <option value="<?= $genre->id_genero ?>" <?= ($book->id_genero == $genre->id_genero) ? 'selected' : '' ?>>
                        <?= htmlspecialchars($genre->genero, ENT_QUOTES, 'UTF-8'); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="mb-3">
            <label for="imagen_url" class="form-label">URL de la Imagen</label>
            <input type="text" class="form-control" id="imagen_url" name="imagen_url" required>
        </div>


        <div class="text-end">
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
            <a href="home" class="btn btn-secondary">Cancelar</a>
        </div>
    </form>
</div>