<?php require 'templates/layouts/header.phtml' ?>

<div class="container mt-4">
    <h1 class="text-center mb-4">Agregar Libro</h1>
    <?php if (!empty($errors)): ?>
        <div class="alert alert-danger">
            <ul>
                <?php foreach ($errors as $error): ?>
                    <li><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>

    <form action="addBook" method="POST">

        <div class="mb-3">
            <label for="title" class="form-label">Título</label>
            <input type="text" class="form-control" id="title" name="title" required>
        </div>
        <div class="mb-3">
            <label for="sinopsis" class="form-label">Sinopsis</label>
            <textarea class="form-control" id="sinopsis" name="sinopsis" required></textarea>
        </div>
        <div class="mb-3">
            <label for="autor" class="form-label">Autor</label>
            <input type="text" class="form-control" id="autor" name="autor" required>
        </div>
        <div class="mb-3">
            <label for="anio" class="form-label">Año de Publicación</label>
            <input type="number" class="form-control" id="anio" name="anio" required>
        </div>
        <div class="mb-3">
            <label for="genero" class="form-label">Género</label>
            <select id="id_genero" name="id_genero">
                <option value="">Seleccionar género</option>
                <?php foreach ($genres as $genre): ?>
                    <option value="<?= $genre->id_genero ?>" <?= isset($_POST['id_genero']) && $_POST['id_genero'] == $genre->id_genero ? 'selected' : '' ?>>
                        <?= $genre->genero ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="mb-3">
            <label for="imagen_url" class="form-label">URL de la Imagen</label>
            <input type="text" class="form-control" id="imagen_url" name="imagen_url" required>
        </div>

        <button type="submit" class="btn btn-primary">Agregar Libro</button>
    </form>

</div>