<?php
require_once './templates/layouts/header.phtml';
?>
<div class="content mt-4">
    <div class="container">
        <h1 class="text-center mb-4">Lista de Géneros</h1>
        <?php if ($this->user): ?>
            <div class="text-end mb-3">
                <a href="addGenre" class="btn btn-primary">Agregar Género</a>
            </div>
        <?php endif; ?>
        <div class="row">
            <?php foreach ($genres as $genre): ?>
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card shadow-sm h-100">
                        <div class="card-body">
                            <h5 class="card-title"><?= htmlspecialchars(ucfirst($genre->genero), ENT_QUOTES, 'UTF-8') ?></h5>
                            <p class="card-text"><strong>Descripción:</strong> <?= htmlspecialchars($genre->descripcion, ENT_QUOTES, 'UTF-8') ?></p>
                            <p class="card-text"><strong>Géneros Relacionados:</strong> <?= htmlspecialchars($genre->generos_relacionados, ENT_QUOTES, 'UTF-8') ?></p>
                            <p class="card-text"><strong>Nivel de Popularidad:</strong> <?= htmlspecialchars($genre->nivel_popularidad, ENT_QUOTES, 'UTF-8') ?></p>
                            <a href="booksByGenre/<?= htmlspecialchars($genre->id_genero, ENT_QUOTES, 'UTF-8') ?>" class="btn btn-outline-primary mt-3">Ver libros</a>
                            <?php if ($this->user): ?>
                                <a href="updateGenre/<?= $genre->id_genero ?>" class="btn btn-warning mt-3">Modificar</a>

                                <button type="button" class="btn btn-danger mt-3" onclick="confirmDelete('<?= htmlspecialchars($genre->genero, ENT_QUOTES, 'UTF-8'); ?>', 'deleteGenre/<?= $genre->id_genero ?>')">
                                    Eliminar
                                </button>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<script>
    function confirmDelete(genreTitle, deleteUrl) {
        if (confirm("¿Estás seguro de que deseas eliminar el genero \"" + genreTitle + "\"?")) {
            // Crear un formulario para enviar la solicitud de eliminación
            const form = document.createElement('form');
            form.method = 'POST';
            form.action = deleteUrl;
            const input = document.createElement('input');
            input.type = 'hidden';
            input.name = '_method';
            input.value = 'DELETE';
            form.appendChild(input);
            document.body.appendChild(form);
            form.submit();
        }
    }
</script>